site_name: Colin Li's Projects 
site_url: https://colinli02.github.io/Projects/

nav:
    - Coin Robot: CoinRobot.md
    - Micro Controller Projects: MicroControllerProjects.md
    - UDP Network Pinger: UDPNetworkPinger.md
    - Basic HTML Web Server: BasicHTMLWeb.md
    - About: about.md

theme:
  name: material

markdown_extensions:
  - admonition # For !!! noteblocks 
  - pymdownx.snippets: # For quoting using --8<--
      url_download: true