site_name: Colin Li's Projects 
site_url: https://colinli02.github.io/Projects/

nav:
    - Coin Robot: CoinRobot.md
    - Micro Controller Projects: MicroControllerProjects.md
    - About: about.md

theme:
  name: material

markdown_extensions:
  - admonition # For !!! noteblocks 
  - pymdownx.snippets: # For quoting using --8<-- to insert markdown or html only
      url_download: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
