site_name: Colin Li's Projects 
site_url: https://colinli02.github.io/Projects/

nav:
    - Home: index.md
    - About: about.md
    - Micro-Controller: MicroControllerProjects.md
    - Machine Learning: ML_PROJ.md
    - General Software: GEN_PRO_PROJ.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
      # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: dracula
      primary: cyan
      accent: cyan
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/colin-li-426124222/
    - icon: fontawesome/brands/github
      link: https://github.com/colinli02

markdown_extensions:
  - admonition # For !!! noteblocks 
  - pymdownx.snippets: # For quoting using --8<-- to insert markdown or html only
      url_download: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.details
  - pymdownx.snippets